# Site settings
title: Christos Zonios - Portfolio
description: My portfolio page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://czonios.github.io"

# User settings
username: Christos Zonios
user_description: I am a React/Nodejs full stack engineer and Data Science & Engineering M.Sc. student in the Computer Science dept. of the University of Ioannina, Greece.<br/>I am really good at solving problems and learning new things.<br/><strong>I like the hands on approach</strong> - <em>I figure out what needs to be done, and I do it.</em><br/>Take a look through some of my <a class="link" href="#projects" data-scroll>projects</a>.<br/>Feel free to check out my <a target="_blank" href="https://github.com/czonios">Github</a>. You can always <a href="mailto:czonios@gmail.com">hit me up</a> if you have any questions.
user_title: Full Stack Engineer & Data Scientist

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
