header_pages:
    - index.md
    - research.md
    - blog.md

footer: 'follow me on <a href="https://github.com/czonios">GitHub</a>'

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # true or false (default)

gem "github-pages", "219", group: :jekyll_plugins

plugins:
    - jekyll-seo-tag

name: "Christos Zonios | Portfolio"
title: "Portfolio"
description: "Get to know me and my research"
meta_description: "Neuromorphic Computing, Deep Learning, IoT and Linux"
google_analytics: UA-112579131-1

# logo: "/assets/img/favicon.jpeg"
#paginate: 15
comments: false
siteurl: https://czonios.github.io
baseurl: "/"
domain_name: "https://czonios.github.io"
gems:
    #   - jekyll-paginate
    - jekyll-github-metadata

# Details for the RSS feed generator
url: "https://czonios.github.io/blog"
author: "Christos Zonios"
lsi: false
safe: true
source: /
# incremental: false
# highlighter: rouge
# gist:
#     noscript: false
# markdown: kramdown
# #mathjax: true
# kramdown:
# #    math_engine: katex
#     syntax_highlighter: rouge
